# Autogenerated by devscripts/update-version.py

__version__ = '2024.01.14.232710'

RELEASE_GIT_HEAD = '8e6e3651727b0b85764857fc6329fe5e0a3f00de'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2024.01.14.232710dev'
