
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-15T20:15:53+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "20cbdd2a1dd9a14f4072ba975cc4f3ca805e88cd",
 "version": "0.7.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
