
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-17T20:35:54+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c05cc9e8327f19f8b17df076e3c35fb4408a2604",
 "version": "8.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
