# coding: utf-8

"""
    BeeKeeperAI EscrowAI Enclave API

    Described below is the EscrowAI Enclave API that provides functionality inside a BeeKeeperAI environment. Included are data engineering endpoints and reporting endpoints.

    The version of the OpenAPI document: 1.5.1
    Contact: engineering@beekeeperai.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from BeeKeeperRuntimeSDK.api.run_api import RunApi


class TestRunApi(unittest.TestCase):
    """RunApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RunApi()

    def tearDown(self) -> None:
        pass

    def test_api_v1_algorithm_status_post(self) -> None:
        """Test case for api_v1_algorithm_status_post

        Log the status of an algorithm execution
        """
        pass


if __name__ == '__main__':
    unittest.main()
