# coding: utf-8

"""
    BeeKeeperAI EscrowAI Enclave API

    Described below is the EscrowAI Enclave API that provides functionality inside a BeeKeeperAI environment. Included are data engineering endpoints and reporting endpoints.

    The version of the OpenAPI document: 1.5.1
    Contact: engineering@beekeeperai.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from BeeKeeperRuntimeSDK.api.mlflow_api import MlflowApi


class TestMlflowApi(unittest.TestCase):
    """MlflowApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MlflowApi()

    def tearDown(self) -> None:
        pass

    def test_api20_mlflow_proxy_path_delete(self) -> None:
        """Test case for api20_mlflow_proxy_path_delete

        Proxy DELETE request to MLflow
        """
        pass

    def test_api20_mlflow_proxy_path_get(self) -> None:
        """Test case for api20_mlflow_proxy_path_get

        Proxy GET request to MLflow
        """
        pass

    def test_api20_mlflow_proxy_path_post(self) -> None:
        """Test case for api20_mlflow_proxy_path_post

        Proxy POST request to MLflow
        """
        pass

    def test_api20_mlflow_proxy_path_put(self) -> None:
        """Test case for api20_mlflow_proxy_path_put

        Proxy PUT request to MLflow
        """
        pass


if __name__ == '__main__':
    unittest.main()
