
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-18T16:32:17+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "16dd1db5ffd780704bb3f3ca49ab729225f9f604",
 "version": "1.1.0.post0.dev45"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
