# coding: utf-8
# Generated by setup.py for PyCBC on 2024-01-19 13:08:21 +0000.

version = '2.1.3'
date = '2024-01-19 12:15:57 +0000'
release = True
last_release = '2.4.0'

git_hash = '5d4d8bb311db970e2e39a511a02f9765664e1f72'
git_branch = 'None'
git_tag = 'v2.1.3'
git_author = 'Tito Dal Canton <tito.dalcanton@ijclab.in2p3.fr>'
git_committer = 'Tito Dal Canton <tito.dalcanton@ijclab.in2p3.fr>'
git_status = 'CLEAN: All modifications committed'
git_builder = 'Unknown User <>'
git_build_date = '2024-01-19 13:08:21 +0000'
git_verbose_msg = """Version: 2.1.3
Branch: None
Tag: v2.1.3
Id: 5d4d8bb311db970e2e39a511a02f9765664e1f72
Builder: Unknown User <>
Build date: 2024-01-19 13:08:21 +0000
Repository status is CLEAN: All modifications committed"""
from pycbc._version import *
