
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-15T11:03:25-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "2c4daffe0464a5101153496c8ced55d0ee65da7c",
 "version": "0.11.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
