
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-18T11:53:11-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "ee2298651576de0b97e15f5d4c446580d426fd58",
 "version": "0+untagged.332.gee22986"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
