
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-19T11:54:04+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "57a155ae476d9d132f7c825be438ca159945ad17",
 "version": "3.1.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
