
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-18T14:43:44-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "0c63d0c82d7a871864ebb2a7696d228811155003",
 "version": "5.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
