import docker

def set_docker_client(client: docker.DockerClient) -> docker.DockerClient: ...
def get_docker_client() -> docker.DockerClient: ...
def set_docker_api_client(client: docker.APIClient) -> docker.APIClient: ...
def get_docker_api_client() -> docker.APIClient: ...
