# coding: utf-8

"""
    BeeKeeperAI EscrowAI Enclave API

    Described below is the EscrowAI Enclave API that provides functionality inside a BeeKeeperAI environment. Included are data engineering endpoints and reporting endpoints.

    The version of the OpenAPI document: 1.5.1
    Contact: engineering@beekeeperai.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
from unittest.mock import MagicMock
import datetime
import json

import BeeEnclave
from BeeEnclave.models.api_v1_report_post200_response import ApiV1ReportPost200Response  # noqa: E501
from BeeEnclave.rest import ApiException
from BeeEnclave.api_client import ApiClient

class TestApiV1ReportPost200Response(unittest.TestCase):
    """ApiV1ReportPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ApiV1ReportPost200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1ReportPost200Response`
        """
        model = BeeEnclave.models.api_v1_report_post200_response.ApiV1ReportPost200Response()  # noqa: E501
        if include_optional :
            return ApiV1ReportPost200Response(
                message = ''
            )
        else :
            return ApiV1ReportPost200Response(
                message = '',
        )
        """

    def testApiV1ReportPost200Response(self):
        """Test ApiV1ReportPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

        api_v1_report_post200_response_json = None

        if api_v1_report_post200_response_json is None:
            return

        response_mock = MagicMock()
        response_mock.data = json.dumps(api_v1_report_post200_response_json)

        deserialized = ApiClient().deserialize(response_mock, ApiV1ReportPost200Response)

        assert deserialized is not None

if __name__ == '__main__':
    unittest.main()
