# coding: utf-8

"""
    BeeKeeperAI EscrowAI Enclave API

    Described below is the EscrowAI Enclave API that provides functionality inside a BeeKeeperAI environment. Included are data engineering endpoints and reporting endpoints.

    The version of the OpenAPI document: 1.5.1
    Contact: engineering@beekeeperai.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from BeeEnclave.api.report_api import ReportApi


class TestReportApi(unittest.TestCase):
    """ReportApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ReportApi()

    def tearDown(self) -> None:
        pass

    def test_api_v1_report_post(self) -> None:
        """Test case for api_v1_report_post

        Post a valid report
        """
        pass

    def test_api_v1_validate_post(self) -> None:
        """Test case for api_v1_validate_post

        Validate a report
        """
        pass


if __name__ == '__main__':
    unittest.main()
