
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-17T13:42:29+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "431cef03c463effd4c19ae4b68a26c9827ae387a",
 "version": "1.20.0.post0.dev70"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
