# This file is automatically generated, DO NOT EDIT
# fmt: off

from os.path import abspath, join, dirname, exists
_root = abspath(dirname(__file__))

# runtime dependencies
import phoenix5._simpropigeon2._init_ctre_simpropigeon2
import phoenix5._simprocancoder._init_ctre_simprocancoder
import phoenix5._simprotalonfx._init_ctre_simprotalonfx
import phoenix5._simcancoder._init_ctre_simcancoder
import phoenix5._simtalonfx._init_ctre_simtalonfx
import phoenix5._simpigeonimu._init_ctre_simpigeonimu
import phoenix5._simtalonsrx._init_ctre_simtalonsrx
import phoenix5._simvictorspx._init_ctre_simvictorspx
