# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['nextpy',
 'nextpy.ai',
 'nextpy.ai.agent',
 'nextpy.ai.agent.agentbox',
 'nextpy.ai.engine',
 'nextpy.ai.engine.library',
 'nextpy.ai.engine.llms',
 'nextpy.ai.engine.llms.caches',
 'nextpy.ai.engine.llms.transformers',
 'nextpy.ai.finetune',
 'nextpy.ai.memory',
 'nextpy.ai.models.audio',
 'nextpy.ai.models.audio.speech_to_text',
 'nextpy.ai.models.audio.text_to_speech',
 'nextpy.ai.models.embedding',
 'nextpy.ai.models.image',
 'nextpy.ai.models.llm',
 'nextpy.ai.rag',
 'nextpy.ai.rag.document_loaders',
 'nextpy.ai.rag.document_loaders.airtable',
 'nextpy.ai.rag.document_loaders.apify.actor',
 'nextpy.ai.rag.document_loaders.apify.dataset',
 'nextpy.ai.rag.document_loaders.asana',
 'nextpy.ai.rag.document_loaders.azcognitive_search',
 'nextpy.ai.rag.document_loaders.azstorage_blob',
 'nextpy.ai.rag.document_loaders.bilibili',
 'nextpy.ai.rag.document_loaders.boarddocs',
 'nextpy.ai.rag.document_loaders.chatgpt_plugin',
 'nextpy.ai.rag.document_loaders.chroma',
 'nextpy.ai.rag.document_loaders.confluence',
 'nextpy.ai.rag.document_loaders.couchdb',
 'nextpy.ai.rag.document_loaders.dad_jokes',
 'nextpy.ai.rag.document_loaders.database',
 'nextpy.ai.rag.document_loaders.deeplake',
 'nextpy.ai.rag.document_loaders.discord',
 'nextpy.ai.rag.document_loaders.docugami',
 'nextpy.ai.rag.document_loaders.elasticsearch',
 'nextpy.ai.rag.document_loaders.faiss',
 'nextpy.ai.rag.document_loaders.feedly_rss',
 'nextpy.ai.rag.document_loaders.feishu_docs',
 'nextpy.ai.rag.document_loaders.file',
 'nextpy.ai.rag.document_loaders.file.audio',
 'nextpy.ai.rag.document_loaders.file.audio_gladia',
 'nextpy.ai.rag.document_loaders.file.cjk_pdf',
 'nextpy.ai.rag.document_loaders.file.deepdoctection',
 'nextpy.ai.rag.document_loaders.file.docx',
 'nextpy.ai.rag.document_loaders.file.epub',
 'nextpy.ai.rag.document_loaders.file.flat_pdf',
 'nextpy.ai.rag.document_loaders.file.image',
 'nextpy.ai.rag.document_loaders.file.image_blip',
 'nextpy.ai.rag.document_loaders.file.image_blip2',
 'nextpy.ai.rag.document_loaders.file.image_deplot',
 'nextpy.ai.rag.document_loaders.file.ipynb',
 'nextpy.ai.rag.document_loaders.file.json',
 'nextpy.ai.rag.document_loaders.file.markdown',
 'nextpy.ai.rag.document_loaders.file.mbox',
 'nextpy.ai.rag.document_loaders.file.paged_csv',
 'nextpy.ai.rag.document_loaders.file.pandas_csv',
 'nextpy.ai.rag.document_loaders.file.pandas_excel',
 'nextpy.ai.rag.document_loaders.file.pdf',
 'nextpy.ai.rag.document_loaders.file.pdf_miner',
 'nextpy.ai.rag.document_loaders.file.pptx',
 'nextpy.ai.rag.document_loaders.file.pymu_pdf',
 'nextpy.ai.rag.document_loaders.file.rdf',
 'nextpy.ai.rag.document_loaders.file.simple_csv',
 'nextpy.ai.rag.document_loaders.file.unstructured',
 'nextpy.ai.rag.document_loaders.firebase_realtimedb',
 'nextpy.ai.rag.document_loaders.firestore',
 'nextpy.ai.rag.document_loaders.github_repo',
 'nextpy.ai.rag.document_loaders.github_repo_issues',
 'nextpy.ai.rag.document_loaders.gmail',
 'nextpy.ai.rag.document_loaders.google_calendar',
 'nextpy.ai.rag.document_loaders.google_docs',
 'nextpy.ai.rag.document_loaders.google_drive',
 'nextpy.ai.rag.document_loaders.google_keep',
 'nextpy.ai.rag.document_loaders.google_sheets',
 'nextpy.ai.rag.document_loaders.gpt_repo',
 'nextpy.ai.rag.document_loaders.graphdb_cypher',
 'nextpy.ai.rag.document_loaders.graphql',
 'nextpy.ai.rag.document_loaders.hatena_blog',
 'nextpy.ai.rag.document_loaders.hubspot',
 'nextpy.ai.rag.document_loaders.huggingface.fs',
 'nextpy.ai.rag.document_loaders.intercom',
 'nextpy.ai.rag.document_loaders.jira',
 'nextpy.ai.rag.document_loaders.joplin',
 'nextpy.ai.rag.document_loaders.jsondata',
 'nextpy.ai.rag.document_loaders.kaltura.esearch',
 'nextpy.ai.rag.document_loaders.kibela',
 'nextpy.ai.rag.document_loaders.make_com',
 'nextpy.ai.rag.document_loaders.mangoapps_guides',
 'nextpy.ai.rag.document_loaders.maps',
 'nextpy.ai.rag.document_loaders.memos',
 'nextpy.ai.rag.document_loaders.metal',
 'nextpy.ai.rag.document_loaders.milvus',
 'nextpy.ai.rag.document_loaders.mondaydotcom',
 'nextpy.ai.rag.document_loaders.mongo',
 'nextpy.ai.rag.document_loaders.notion',
 'nextpy.ai.rag.document_loaders.obsidian',
 'nextpy.ai.rag.document_loaders.opendal_reader',
 'nextpy.ai.rag.document_loaders.opendal_reader.azblob',
 'nextpy.ai.rag.document_loaders.opendal_reader.gcs',
 'nextpy.ai.rag.document_loaders.opendal_reader.s3',
 'nextpy.ai.rag.document_loaders.outlook_localcalendar',
 'nextpy.ai.rag.document_loaders.pandas_ai',
 'nextpy.ai.rag.document_loaders.papers.arxiv',
 'nextpy.ai.rag.document_loaders.papers.pubmed',
 'nextpy.ai.rag.document_loaders.pinecone',
 'nextpy.ai.rag.document_loaders.qdrant',
 'nextpy.ai.rag.document_loaders.readwise',
 'nextpy.ai.rag.document_loaders.reddit',
 'nextpy.ai.rag.document_loaders.remote',
 'nextpy.ai.rag.document_loaders.remote_depth',
 'nextpy.ai.rag.document_loaders.s3',
 'nextpy.ai.rag.document_loaders.singlestore',
 'nextpy.ai.rag.document_loaders.slack',
 'nextpy.ai.rag.document_loaders.snscrape_twitter',
 'nextpy.ai.rag.document_loaders.spotify',
 'nextpy.ai.rag.document_loaders.stackoverflow',
 'nextpy.ai.rag.document_loaders.steamship',
 'nextpy.ai.rag.document_loaders.string_iterable',
 'nextpy.ai.rag.document_loaders.trello',
 'nextpy.ai.rag.document_loaders.twitter',
 'nextpy.ai.rag.document_loaders.weather',
 'nextpy.ai.rag.document_loaders.weaviate',
 'nextpy.ai.rag.document_loaders.web.async_web',
 'nextpy.ai.rag.document_loaders.web.beautiful_soup_web',
 'nextpy.ai.rag.document_loaders.web.knowledge_base',
 'nextpy.ai.rag.document_loaders.web.readability_web',
 'nextpy.ai.rag.document_loaders.web.rss',
 'nextpy.ai.rag.document_loaders.web.simple_web',
 'nextpy.ai.rag.document_loaders.web.sitemap',
 'nextpy.ai.rag.document_loaders.web.trafilatura_web',
 'nextpy.ai.rag.document_loaders.web.unstructured_web',
 'nextpy.ai.rag.document_loaders.whatsapp',
 'nextpy.ai.rag.document_loaders.wikipedia',
 'nextpy.ai.rag.document_loaders.wordlift',
 'nextpy.ai.rag.document_loaders.wordpress',
 'nextpy.ai.rag.document_loaders.youtube_transcript',
 'nextpy.ai.rag.document_loaders.zendesk',
 'nextpy.ai.rag.document_loaders.zulip',
 'nextpy.ai.rag.text_retrievers',
 'nextpy.ai.rag.text_retrievers.document_compressors',
 'nextpy.ai.rag.utilities',
 'nextpy.ai.scripts',
 'nextpy.ai.tests',
 'nextpy.ai.tests.agent',
 'nextpy.ai.tests.engine',
 'nextpy.ai.tests.engine.caches',
 'nextpy.ai.tests.engine.library',
 'nextpy.ai.tests.engine.llms',
 'nextpy.ai.tests.engine.llms.transformers',
 'nextpy.ai.tokenizers',
 'nextpy.ai.tools',
 'nextpy.ai.tools.toolkits',
 'nextpy.ai.tools.toolkits.SQLDb',
 'nextpy.ai.tools.toolkits.Spark_SQLDb',
 'nextpy.ai.tools.toolkits.file_toolkit',
 'nextpy.ai.tools.toolkits.file_toolkit.file',
 'nextpy.ai.tools.toolkits.gmail_toolkit',
 'nextpy.ai.tools.toolkits.gmail_toolkit.gmail',
 'nextpy.ai.tools.toolkits.google_calendar_toolkit',
 'nextpy.ai.tools.toolkits.google_calendar_toolkit.google_calendar',
 'nextpy.ai.tools.toolkits.json_toolkit',
 'nextpy.ai.tools.toolkits.json_toolkit.json',
 'nextpy.ai.tools.toolkits.notion_toolkit',
 'nextpy.ai.tools.toolkits.notion_toolkit.notion',
 'nextpy.ai.tools.toolkits.openapi_toolkit',
 'nextpy.ai.tools.toolkits.requests_toolkit',
 'nextpy.ai.tools.toolkits.requests_toolkit.requests',
 'nextpy.ai.tools.toolkits.slack_toolkit',
 'nextpy.ai.tools.toolkits.slack_toolkit.slack',
 'nextpy.ai.tools.toolkits.slack_toolkit.slack_tool',
 'nextpy.ai.tools.toolkits.zapier_toolkit',
 'nextpy.ai.tools.toolkits.zapier_toolkit.zapier',
 'nextpy.ai.utils',
 'nextpy.backend',
 'nextpy.backend.deploy',
 'nextpy.backend.middleware',
 'nextpy.backend.module',
 'nextpy.backend.module.email',
 'nextpy.build',
 'nextpy.build.compiler',
 'nextpy.constants',
 'nextpy.data',
 'nextpy.data.vectordb',
 'nextpy.frontend',
 'nextpy.frontend.blueprints',
 'nextpy.frontend.components',
 'nextpy.frontend.components.base',
 'nextpy.frontend.components.chakra',
 'nextpy.frontend.components.chakra.datadisplay',
 'nextpy.frontend.components.chakra.disclosure',
 'nextpy.frontend.components.chakra.feedback',
 'nextpy.frontend.components.chakra.forms',
 'nextpy.frontend.components.chakra.layout',
 'nextpy.frontend.components.chakra.media',
 'nextpy.frontend.components.chakra.navigation',
 'nextpy.frontend.components.chakra.overlay',
 'nextpy.frontend.components.chakra.typography',
 'nextpy.frontend.components.core',
 'nextpy.frontend.components.core.layout',
 'nextpy.frontend.components.el',
 'nextpy.frontend.components.el.constants',
 'nextpy.frontend.components.el.elements',
 'nextpy.frontend.components.framer',
 'nextpy.frontend.components.framer.motion',
 'nextpy.frontend.components.glide_datagrid',
 'nextpy.frontend.components.gridjs',
 'nextpy.frontend.components.leaflet',
 'nextpy.frontend.components.markdown',
 'nextpy.frontend.components.media',
 'nextpy.frontend.components.moment',
 'nextpy.frontend.components.next',
 'nextpy.frontend.components.plotly',
 'nextpy.frontend.components.proxy',
 'nextpy.frontend.components.radix',
 'nextpy.frontend.components.radix.primitives',
 'nextpy.frontend.components.radix.themes',
 'nextpy.frontend.components.radix.themes.components',
 'nextpy.frontend.components.radix.themes.layout',
 'nextpy.frontend.components.radix.themes.typography',
 'nextpy.frontend.components.react_player',
 'nextpy.frontend.components.recharts',
 'nextpy.frontend.components.suneditor',
 'nextpy.frontend.components.tags',
 'nextpy.frontend.custom_components',
 'nextpy.frontend.templates.apps.base.code',
 'nextpy.frontend.templates.apps.base.code.components',
 'nextpy.frontend.templates.apps.base.code.pages',
 'nextpy.frontend.templates.apps.base.code.templates',
 'nextpy.frontend.templates.apps.blank.code',
 'nextpy.frontend.templates.apps.hello.code',
 'nextpy.frontend.templates.apps.hello.code.pages',
 'nextpy.frontend.templates.apps.hello.code.states',
 'nextpy.frontend.templates.apps.hello.code.webui',
 'nextpy.frontend.templates.apps.hello.code.webui.components',
 'nextpy.tester',
 'nextpy.utils']

package_data = \
{'': ['*'],
 'nextpy.ai.engine': ['resources/*'],
 'nextpy.frontend': ['templates/apps/base/*',
                     'templates/apps/base/assets/*',
                     'templates/apps/blank/assets/*',
                     'templates/apps/hello/*',
                     'templates/apps/hello/assets/*',
                     'templates/jinja/app/*',
                     'templates/jinja/custom_components/*',
                     'templates/jinja/web/*',
                     'templates/jinja/web/pages/*',
                     'templates/jinja/web/styles/*',
                     'templates/jinja/web/utils/*',
                     'templates/web/*',
                     'templates/web/components/nextpy/*',
                     'templates/web/styles/*',
                     'templates/web/styles/code/*',
                     'templates/web/utils/*',
                     'templates/web/utils/helpers/*']}

install_requires = \
['alembic>=1.11.1,<2.0.0',
 'charset-normalizer>=3.3.2,<4.0.0',
 'cloudpickle>=2.2.1,<3.0.0',
 'fastapi>=0.96.0,<0.97.0',
 'gunicorn>=20.1.0,<21.0.0',
 'httpx>=0.24.0,<0.26.0',
 'jinja2>=3.1.2,<4.0.0',
 'packaging>=23.1,<24.0',
 'pipdeptree>=2.13.0,<3.0.0',
 'platformdirs>=3.10.0,<4.0.0',
 'psutil>=5.9.4,<6.0.0',
 'pydantic>=1.10.2,<2.0.0',
 'pyjokes>=0.6.0,<0.7.0',
 'pylint>=3.0.3,<4.0.0',
 'python-engineio!=4.6.0',
 'python-multipart>=0.0.5,<0.0.6',
 'python-socketio>=5.7.0,<6.0.0',
 'redis>=4.3.5,<5.0.0',
 'rich>=13.0.0,<14.0.0',
 'sqlmodel>=0.0.14,<0.0.15',
 'starlette-admin>=0.9.0,<0.10.0',
 'tabulate>=0.9.0,<0.10.0',
 'typer>=0.4.2,<1',
 'watchdog>=2.3.1,<3.0.0',
 'watchfiles>=0.19.0,<0.20.0',
 'websockets>=10.4']

extras_require = \
{':python_version < "3.11"': ['wrapt>=1.11.0,<2.0.0'],
 ':python_version < "3.12"': ['uvicorn>=0.20.0,<0.21.0'],
 ':python_version >= "3.11"': ['wrapt>=1.14.0,<2.0.0'],
 ':python_version >= "3.12"': ['uvicorn>=0.24.0,<0.25.0'],
 ':sys_platform == "linux"': ['distro>=1.8.0,<2.0.0']}

entry_points = \
{'console_scripts': ['nextpy = nextpy.cli:cli']}

setup_kwargs = {
    'name': 'nextpy',
    'version': '0.3.2',
    'description': "⚡The Pure Python Framework for Web Apps, Meticulously Optimized for 🤖AI agents🤖. World's first AMS🥇",
    'long_description': '<div align="center">\n<img src="https://raw.githubusercontent.com/dotagent-ai/assets/main/nextpy_logo_light_theme.svg#gh-light-mode-only" alt="Nextpy Logo" width="320px">\n\n<p align="center">\n    <a href="docs/🌎/繁體中文/README.md">繁體中文</a>\n    .\n    <a href="docs/🌎/简体中文/README.md">简体中文 </a>\n    .\n    <a href="docs/🌎/Français/README.md">Français </a>\n    ·\n    <a href="docs/🌎/German/README.md">German</a>\n    ·\n    <a href="docs/🌎/Italiano/README.md">Italiano</a>\n    ·\n    <a href="docs/🌎/Português/README.md">Português</a>\n    ·\n    <a href="docs/🌎/Tamil/README.md">Tamil</a>\n    ·\n    <a href="docs/🌎/Ukrainian/README.md">Ukrainian</a>\n    ·\n    <a href="docs/🌎/русский/README.md">русский</a>\n    ·\n    <a href="docs/🌎/عربي/README.md">عربي</a>\n    ·\n    <a href="docs/🌎/Español/README.md">Español</a>\n    ·\n    <a href="docs/🌎/हिंदी/README.md">हिंदी</a>\n    ·\n    <a href="docs/🌎/Türkçe/README.md">Türkçe</a>\n    ·\n    <a href="docs/🌎/한국어/README.md">한국어</a>\n    \n  </p>\n<br>\n\n<a href="https://discord.gg/asTZktHrcH" target="blank">\n<img alt="Discord" src="https://img.shields.io/discord/1111984809821089883?style=for-the-badge&logo=discord&logoColor=white&label=Live%20Support%20%26%20Coding%20Bots%20on%20Discord&labelColor=%23684DFF&link=https%3A%2F%2Fdiscord.gg%2FasTZktHrcH">\n\n</a>\n\n![-----------------------------------------------------](https://res.cloudinary.com/dzznkbdrb/image/upload/v1694798498/divider_1_rej288.gif)\n\n<h3><i>Streamlit\'s simplicity (but 4-10x faster) + FastAPI\'s full power + (Pydantic & SQL Alchemy)\'s robustness</i></h3>\n   \n\n```diff\n+ 🤖 Searching for \'OpenAMS\' or \'OpenAgent\'? They\'re now seamlessly integrated into Nextpy. +\n```\n\n</div>\n\n## 🤩 Nextpy : Fast, Pure Pythonic Web Apps\n\nBuild any web app —effortlessly and quickly ⚡. It simplifies Pythonic development for everything from backends to frontends (yes, visually 🦚stunning frontends in Python!), AI integrations, APIs, and beyond—empowering both humans and AI agents.\n\nNextpy is designed to solve compatibility issues and improve code generation. It is built on our insight🔍 that the choice of underlying frameworks significantly affects the efficiency of AI code generation, regardless of other factors such as LLMs, prompts, or fine-tuning methods.\n\n- ⏰ **What You Can Build in 1 hour:** Beautiful portfolios, dashboards, portals, data apps, internal tools, APIs etc.\n\n- 📚 ***& The best part? Transferable Knowledge:*** Building with nextpy `progressively` teaches you framework-agnostic fundamentals and the best python libraries- FastAPI, Pydantic, SQLModel, Pandas, Jinja2, SQLAlchemy, etc.\n\n- ⚡ **4-10x faster than Streamlit:** Our compiled app achieves a staggering 4-10x performance leap over Streamlit. See the difference for yourself at [nextpy.org](https://nextpy.org), boasting a PageSpeed score of 99/100\n![image](https://res.cloudinary.com/doojikdqd/image/upload/v1704975583/github_nextpy/file_2024-01-11_11.30.21_dqfcx3.png)\n\n\n![-----------------------------------------------------](https://res.cloudinary.com/dzznkbdrb/image/upload/v1694798498/divider_1_rej288.gif)\n\n## 💡 Key Features\n\n### Simplifying App Development:🧩\n- **🐍 Unleash Python\'s Full Potential** - Eliminate complexities and build everything—frontend and backend—in Python, seamlessly integrating any Python library.\n\n- **🎨 Rich UI Library** - Over 100 fully customizable built-in components for rapid UI development.\n\n- **⚛️ Tap into React\'s Power with Pythonic Wrappers** - Harness the vast React ecosystem directly within Python, utilizing any React library **_without JavaScript knowledge._**\n\n- **🚀 Built-in Performance Optimizations** - Deliver exceptional user experiences with automatic image, font, and script optimizations for lightning-fast loading speeds and responsiveness. See the difference for yourself at [nextpy.org](https://nextpy.org).\n\n- **👁️\u200d🗨️ Accessibility Out of the Box** - Achieving accessibility can be complex. We\'ve selected the best UI React components, like Radix, to ensure accessibility is a standard feature, not an afterthought.\n\n![image](https://res.cloudinary.com/doojikdqd/image/upload/v1704936923/github_nextpy/accessible-nextpy_ij7lqu.gif)\n\n\n### Better AI Generations: \u200d🤖\n\n- **🧠 More Effective Than Chaining or Prompt Engineering** - Next.py aligns with LLM processing patterns, enabling precise output control and optimal model utilization.\n\n- **💡 Optimized for Code Generation** - Regardless of the LLMs, prompts, or fine-tuning used, the underlying app framework significantly impacts the efficiency of code generation. Next.py\'s architecture is specifically engineered to maximize efficiency.\n\n- **💾 Session State with LLM** - Efficiently maintain state with LLMs, leveraging KV caches to convert multiple output tokens into prompt token batches. This approach reduces redundant generations, accelerating the handling of lengthy and intricate prompts. **_(only for open-source models)_**\n\n- **🧪 Detect Syntax Errors**: Test LLM-generated code, identifying and correcting LLM hallucinations, invalid Nextpy methods, and automatically generating prompts for seamless fixes.\n\n### Developer-First: ❤️\n\n- **📘 Transferable Knowledge** - Learning Next.py teaches you framework-agnostic fundamentals and the best Python libraries, improving your python development expertise and enabling you to excel across any framework.\n\n- **🛠️ Extensible** - If you know how to do something in Python or plain English, you can integrate it with nextpy.\n\n![-----------------------------------------------------](https://res.cloudinary.com/dzznkbdrb/image/upload/v1694798498/divider_1_rej288.gif)\n\n## 🚀 Quick Start (3 mins)\n\n[![Build a python webapp in 3 minutes](https://github.com/anubrag/nextpy/assets/25473195/c41ea5b7-d270-451a-a0d0-8308ff9dbfdc)](https://www.youtube.com/watch?v=5Ex-c9wwiYE)\n\n\n**1. Installing Nextpy**\n\nOpen your terminal and prepare for an adventure of a lifetime!\n\n```bash\npip install nextpy\n```\n\n**(Remember, Python 3.7 or later is required.)**\n\n**2. Initializing Your App**\n\nNavigate to the desired directory for your project in the terminal. Use the `nextpy init` command to initialize a template app in your new directory.\n\n```bash\nnextpy init\n```\n\n**3. Choose your template:**\n\nFor now, just press enter to automatically default to the blank template.\n```md\n    Blank Template: A simple single page template\n    Base Template: A multi-page app with a sidebar\n```\n\n**4. Running the App**\n\nIn the same directory where you previously ran nextpy init, enter the following command:\n\n```bash\nnextpy run\n```\n\n**5. View the App:**\n\nCheck out your app by visiting [http://localhost:3000](http://localhost:3000)\n\n> [!NOTE]\n> Your application is now fully functional. To view the frontend, navigate to `localhost:3000`. The backend server is accessible at `localhost:8000`.\n> While it\'s unlikely you\'ll ever directly interact with it, the backend API documentation can be found at `localhost:8000/docs`, and the openapi.json file is located at `localhost:8000/openapi.json`.\n\n\n## 🎨 Start with a template!\n\nWe speedup your development with a [ever growing list of community templates](https://github.com/dot-agent/nextpy/tree/main/app-examples). Some examples:\n\n<table border="0">\n  <tr>\n    <td>\n      <a target="_blank" href="https://nextpy.org/">\n        <img src="https://res.cloudinary.com/doojikdqd/image/upload/v1703429508/github_nextpy/glide_datagrid_2x_fdxoyy.png" style="max-height:150px; width:auto; display:block;">\n      </a>\n    </td>\n    <td>\n      <a target="_blank" href="https://nextpy.org/">\n        <img src="https://res.cloudinary.com/doojikdqd/image/upload/v1703429508/github_nextpy/portfolio_2x_y4lzet.png" style="max-height:150px; width:auto; display:block;">\n      </a>\n    </td>\n     <td>\n      <a target="_blank" href="https://nextpy.org/">\n        <img src="https://res.cloudinary.com/doojikdqd/image/upload/v1703429509/github_nextpy/chart_2x_eh0q9x.png" style="max-height:150px; width:auto; display:block;">\n      </a>\n    </td>\n     <td>\n      <a target="_blank" href="https://nextpy.org/">\n        <img src="https://res.cloudinary.com/doojikdqd/image/upload/v1703429509/github_nextpy/chat_app_2x_cmsaht.png" style="max-height:150px; width:auto; display:block;">\n      </a>\n    </td>\n     <td>\n      <a target="_blank" href="https://nextpy.org/">\n        <img src="https://res.cloudinary.com/doojikdqd/image/upload/v1703429509/github_nextpy/crud_2x_bcxiyp.png" style="max-height:150px; width:auto; display:block;">\n      </a>\n    </td>\n     <td>\n      <a target="_blank" href="https://nextpy.org/">\n        <img src="https://res.cloudinary.com/doojikdqd/image/upload/v1703429508/github_nextpy/login_2x_hgjpo2.png" style="max-height:150px; width:auto; display:block;">\n      </a>\n    </td>\n  </tr>\n  <tr>\n    <td>Powerful tables</td>\n    <td>Portfolio Sites</td>\n    <td>Interactive Charts</td>\n    <td>AI chat</td>\n    <td>Crud Apps</td>\n    <td>Onboarding</td>\n  </tr>\n</table>\n\n### Setting Up the Template\n1. Copy the template files to your local folder.\n2. Install necessary dependencies with **`pip install -r requirements.txt`**.\n3. Initialize your app by running **`nextpy init`**.\n4. Launch the app with **`nextpy run`** to see it in action. To check the site visit `localhost:3000`\n\n\n# ➖ or ➖ \n---\n\n### 🤣 Building a Joke Generator App (5 mins)\n\nEdit `myapp/myapp.py` to create your app.\n\n#### 1. Import Libraries\n\n```python\nimport nextpy as xt\nimport pyjokes\n```\n\nStart by importing `nextpy` for development and `pyjokes` for random jokes.\n\n#### 2. Set Up the App State\n\n```python\nclass State(xt.State):\n    joke: str = "Click the button to get a joke!"\n\n    def generate_joke(self):\n        self.joke = pyjokes.get_joke()\n```\n\nCreate a `State` class with a `joke` variable. Use `generate_joke` to fetch new jokes.\n\n#### 3. Design the Main Page\n\n```python\ndef index():\n    layout = xt.vstack(\n        xt.text(State.joke, font_size="2em"),\n        xt.button("Generate Joke", on_click=State.generate_joke),\n    )\n    return layout\n```\n\nThe `index` function arranges a joke display and a button. `vstack` is used to stack components vertically, while `hstack` is used to stack components horizontally.\n\n#### 4. Optional Styling\n```md\ndef index():\n    layout = xt.vstack(\n        xt.text(State.joke, font_size="2em"),\n        xt.button("Generate Joke", on_click=State.generate_joke),\n\n        spacing="1em",\n        align_items="center",\n        justify_content="center",\n        height="100vh",\n   )\n    return layout\n```\nThe `spacing` attribute adds space between the `text` and `button` elements, while `align_items` and `justify_content` ensure that these elements are centered. The stack\'s `height` is set to 100% of the Viewport Height (`100vh`), which allows the vertical stack to fill the entire height of your screen.\n\n#### 5. Setup the app\n\n```python\napp = xt.App()\napp.add_page(index)\n\n```\n\nSet up the app, add the main page. To view the frontend, navigate to `localhost:3000`. \n\n\n![-----------------------------------------------------](https://res.cloudinary.com/dzznkbdrb/image/upload/v1694798498/divider_1_rej288.gif)\n\n\n## 🛣️ Project Roadmap\n\n**🌟 Upcoming Features**\n\n1. **Frontend Magic Components**\n   - 🪄 **PDF Resume to Personal Site**: Create a "magic component" that converts PDF resumes into customizable, full-stack personal websites.\n\n2. **Backend Modules**\n   - 🔐 **User Authentication and Email Integration**: Add modules for robust login functionality and email subscription.\n   - 🛒 **Modules for Blogging and E-commerce**: Add backend modules to facilitate blog management and e-commerce webapps.\n\n3. **Build and Performance Optimization**\n   - 🔧 **Compiler Enhancement with Rust or mojo**: Transitioning our existing compiler to Rust or mojo to achieve faster performance.\n\n4. **Generative AI**\n   - 🐍 **Nextpy LLM**: Build the best Python LLM.\n   - 💬 **End-User Copilot Feature**: A chat-based copilot for app users that lets them interact with your product and do things by text. We have all the modules ready for this, we just need to simplify the abstraction. Just set `copilot = True` in xtconfig and you’re should be good to go.\n\n## 🤗 Get Involved\n\n**We welcome contributors of all skill levels! 🤝**\n\nWant to make a difference? Start by forking our repository and sending in your pull requests. We\'re excited to welcome you to our community. Together, we\'ll craft something truly remarkable! ✨\n\n![-----------------------------------------------------](https://res.cloudinary.com/dzznkbdrb/image/upload/v1694798498/divider_1_rej288.gif)\n\n\n## Why another framework?\nIn our quest to create apps that write themselves, we delved deep into a labyrinth of coding tools, frameworks, and libraries. Our experiments spanned all major large language models (LLMs), thousands of prompts, and every major web development framework, from React to Streamlit.\n\nInsight\n> [!TIP]\n> We found that the choice of the foundational app framework significantly influences code generation efficiency, irrespective of the LLMs, prompts, or fine-tuning methods.\n\nInitially, reflex\'s flexibility seemed promising, aligning with several of our requirements. However, as we experimented with different web apps, crucial feature gaps emerged. Bridging these gaps necessitated extensive "glue code," which dramatically slowed down development.\n\nFor months, we resisted the urge to reinvent the wheel and tried to assemble different tools to bring our vision to life. Instead of creating a framework from scratch, we aimed to create an opinionated app starter kit by selectively incorporating the best features from top frameworks. Although we still view this project as a **full stack app starter kit** rather than a framework, the distinction is becoming somewhat blurred as we have developed several custom modules and made specific design decisions.\n\nThis novel framework merges the simplicity of Streamlit with the speed and adaptability of Next.js. For the backend, we opted for FastAPI for its simplicity, coupled with Pydantic for robust type-checking. Our frontend was crafted using a tailored version of the Reflex library, incorporating new components. Currently, we are in the process of overhauling the core Python-to-JavaScript compiler to optimize speed. Additionally, we embraced SQLModel & SQLAlchemy for database connectivity. Furthermore, we have developed selected features specifically for generative AI. We have created a JSON-based database that uses JSON as the data storage medium, while also providing SQL-like capabilities.\n\n**Our mission?** Make Next.py the most efficient app framework, for humans and AI alike!\n\nWant to know more? Check out our manifesto! https://nextpy.org/manifesto/\n\n## 🙏 Thanks\n\n\nNextpy Framework is a state-of-the-art app development framerwork optimized for AI-based code generation, built on the open-source community’s spirit of cooperation. It integrates key components from landmark projects like Guidance, Llama-Index, FastAPI-Mail, LangChain, ReactPy, Reflex, Chakra, Radix, Numpy and Next.js, while also drawing insights from the React and Rust ecosystems. This fusion ideas has been pivotal in shaping Nextpy into a framework that\'s not just AI-friendly but also a trailblazer in generative web development tools.\n\nWe are deeply grateful to the open-source creators, contributors, and maintainers whose work has provided the basis for Nextpy. Your commitment to innovation and openness has been vital for shaping this framework. Your contributions have not only enhanced Nextpy but are also advancing the new era of AI-powered software development. Thank you for being the catalysts and enablers of this transformational journey.\n',
    'author': 'Team dotagent',
    'author_email': 'anurag@dotagent.ai',
    'maintainer': 'None',
    'maintainer_email': 'None',
    'url': 'https://nextpy.org',
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'extras_require': extras_require,
    'entry_points': entry_points,
    'python_requires': '>=3.8,<4.0',
}


setup(**setup_kwargs)
