# coding: utf-8

"""
    BeeKeeperAI EscrowAI Enclave API

    Described below is the EscrowAI Enclave API that provides functionality inside a BeeKeeperAI environment. Included are data engineering endpoints and reporting endpoints.

    The version of the OpenAPI document: 1.5.1
    Contact: engineering@beekeeperai.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
from unittest.mock import MagicMock
import datetime
import json

import BeeKeeperRuntimeSDK
from BeeKeeperRuntimeSDK.models.sql_response import SQLResponse  # noqa: E501
from BeeKeeperRuntimeSDK.rest import ApiException
from BeeKeeperRuntimeSDK.api_client import ApiClient

class TestSQLResponse(unittest.TestCase):
    """SQLResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SQLResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SQLResponse`
        """
        model = BeeKeeperRuntimeSDK.models.sql_response.SQLResponse()  # noqa: E501
        if include_optional :
            return SQLResponse(
                results = [
                    None
                    ], 
                message = ''
            )
        else :
            return SQLResponse(
                results = [
                    None
                    ],
                message = '',
        )
        """

    def testSQLResponse(self):
        """Test SQLResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

        sql_response_json = {results=[{id=1, name=Goku}], message=Found Goku}

        if sql_response_json is None:
            return

        response_mock = MagicMock()
        response_mock.data = json.dumps(sql_response_json)

        deserialized = ApiClient().deserialize(response_mock, SQLResponse)

        assert deserialized is not None

if __name__ == '__main__':
    unittest.main()
