
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-17T05:55:25-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "75416407d77ef7aa0eb86997d17c0053068decde",
 "version": "5.4.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
