# Generated by Django 4.2.3 on 2023-09-04 21:02

from django.db import migrations, models

def add_display_name(apps, schema_editor):
    Transition = apps.get_model('cosmic_pipeline', 'Transition')
    for transition in Transition.objects.all():
        transition.save()

class Migration(migrations.Migration):
    dependencies = [
        ("cosmic_pipeline", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transition",
            name="display_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Display Name"
            ),
        ),
        migrations.RunPython(add_display_name, migrations.RunPython.noop),
    ]
