# Generated by Django 4.2.9 on 2024-01-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmic_pipeline', '0005_alter_workflow_workflow_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='restrictrulecondition',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transition',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transitionstate',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transitionstate',
            name='terminal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
