# coding: utf-8

"""
    scibec

    scibec  # noqa: E501

    The version of the OpenAPI document: 1.7.4
    Contact: klaus.wakonig@psi.ch
    Generated by: https://openapi-generator.tech
"""

import unittest

import py_scibec_openapi_client
from py_scibec_openapi_client.model.new_event import NewEvent
from py_scibec_openapi_client import configuration


class TestNewEvent(unittest.TestCase):
    """NewEvent unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
