
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-18T19:13:52-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "4073d8cce03962c7e6f692e2e4877d9f72e4e4b7",
 "version": "2024.1.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
