
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-19T14:28:41+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "cbcecb19989769c9fb0c71b6691b84aa748d026f",
 "version": "3.1.24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
