# Generated by Django 3.2.9 on 2022-04-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simo_esphome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espdevice',
            name='firmware_status',
            field=models.CharField(choices=[('up_to_date', 'Up to date'), ('out_of_date', 'Out of date!'), ('compiling', 'Compiling...'), ('needs_update', 'Needs update!'), ('updating', 'Updating...')], db_index=True, default='out_of_date', max_length=50, verbose_name='firmware'),
        ),
    ]
