
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-17T11:04:22+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0ae596004aacfb249d9cbeff994212b4b3dbed82",
 "version": "2.3.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
