# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resemble/v1alpha1/errors.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eresemble/v1alpha1/errors.proto\x12\x11resemble.v1alpha1\"\x19\n\x17\x41\x63torAlreadyConstructed\"3\n\x13\x41\x63torNotConstructed\x12\x1c\n\x14requires_constructor\x18\x01 \x01(\x08\"\x10\n\x0eUnknownServiceb\x06proto3')



_ACTORALREADYCONSTRUCTED = DESCRIPTOR.message_types_by_name['ActorAlreadyConstructed']
_ACTORNOTCONSTRUCTED = DESCRIPTOR.message_types_by_name['ActorNotConstructed']
_UNKNOWNSERVICE = DESCRIPTOR.message_types_by_name['UnknownService']
ActorAlreadyConstructed = _reflection.GeneratedProtocolMessageType('ActorAlreadyConstructed', (_message.Message,), {
  'DESCRIPTOR' : _ACTORALREADYCONSTRUCTED,
  '__module__' : 'resemble.v1alpha1.errors_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.ActorAlreadyConstructed)
  })
_sym_db.RegisterMessage(ActorAlreadyConstructed)

ActorNotConstructed = _reflection.GeneratedProtocolMessageType('ActorNotConstructed', (_message.Message,), {
  'DESCRIPTOR' : _ACTORNOTCONSTRUCTED,
  '__module__' : 'resemble.v1alpha1.errors_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.ActorNotConstructed)
  })
_sym_db.RegisterMessage(ActorNotConstructed)

UnknownService = _reflection.GeneratedProtocolMessageType('UnknownService', (_message.Message,), {
  'DESCRIPTOR' : _UNKNOWNSERVICE,
  '__module__' : 'resemble.v1alpha1.errors_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.UnknownService)
  })
_sym_db.RegisterMessage(UnknownService)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTORALREADYCONSTRUCTED._serialized_start=53
  _ACTORALREADYCONSTRUCTED._serialized_end=78
  _ACTORNOTCONSTRUCTED._serialized_start=80
  _ACTORNOTCONSTRUCTED._serialized_end=131
  _UNKNOWNSERVICE._serialized_start=133
  _UNKNOWNSERVICE._serialized_end=149
# @@protoc_insertion_point(module_scope)
