# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resemble/v1alpha1/transactions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$resemble/v1alpha1/transactions.proto\x12\x11resemble.v1alpha1\"K\n\x0ePrepareRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\x10\n\x08\x61\x63tor_id\x18\x02 \x01(\t\x12\x16\n\x0etransaction_id\x18\x03 \x01(\x0c\"\x11\n\x0fPrepareResponse\"J\n\rCommitRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\x10\n\x08\x61\x63tor_id\x18\x02 \x01(\t\x12\x16\n\x0etransaction_id\x18\x03 \x01(\x0c\"\x10\n\x0e\x43ommitResponse\"I\n\x0c\x41\x62ortRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\x10\n\x08\x61\x63tor_id\x18\x02 \x01(\t\x12\x16\n\x0etransaction_id\x18\x03 \x01(\x0c\"\x0f\n\rAbortResponse\"&\n\x0cWatchRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\x0c\" \n\rWatchResponse\x12\x0f\n\x07\x61\x62orted\x18\x01 \x01(\x08\x32\xfa\x01\n\x0bParticipant\x12P\n\x07Prepare\x12!.resemble.v1alpha1.PrepareRequest\x1a\".resemble.v1alpha1.PrepareResponse\x12M\n\x06\x43ommit\x12 .resemble.v1alpha1.CommitRequest\x1a!.resemble.v1alpha1.CommitResponse\x12J\n\x05\x41\x62ort\x12\x1f.resemble.v1alpha1.AbortRequest\x1a .resemble.v1alpha1.AbortResponse2Y\n\x0b\x43oordinator\x12J\n\x05Watch\x12\x1f.resemble.v1alpha1.WatchRequest\x1a .resemble.v1alpha1.WatchResponseb\x06proto3')



_PREPAREREQUEST = DESCRIPTOR.message_types_by_name['PrepareRequest']
_PREPARERESPONSE = DESCRIPTOR.message_types_by_name['PrepareResponse']
_COMMITREQUEST = DESCRIPTOR.message_types_by_name['CommitRequest']
_COMMITRESPONSE = DESCRIPTOR.message_types_by_name['CommitResponse']
_ABORTREQUEST = DESCRIPTOR.message_types_by_name['AbortRequest']
_ABORTRESPONSE = DESCRIPTOR.message_types_by_name['AbortResponse']
_WATCHREQUEST = DESCRIPTOR.message_types_by_name['WatchRequest']
_WATCHRESPONSE = DESCRIPTOR.message_types_by_name['WatchResponse']
PrepareRequest = _reflection.GeneratedProtocolMessageType('PrepareRequest', (_message.Message,), {
  'DESCRIPTOR' : _PREPAREREQUEST,
  '__module__' : 'resemble.v1alpha1.transactions_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.PrepareRequest)
  })
_sym_db.RegisterMessage(PrepareRequest)

PrepareResponse = _reflection.GeneratedProtocolMessageType('PrepareResponse', (_message.Message,), {
  'DESCRIPTOR' : _PREPARERESPONSE,
  '__module__' : 'resemble.v1alpha1.transactions_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.PrepareResponse)
  })
_sym_db.RegisterMessage(PrepareResponse)

CommitRequest = _reflection.GeneratedProtocolMessageType('CommitRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMMITREQUEST,
  '__module__' : 'resemble.v1alpha1.transactions_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.CommitRequest)
  })
_sym_db.RegisterMessage(CommitRequest)

CommitResponse = _reflection.GeneratedProtocolMessageType('CommitResponse', (_message.Message,), {
  'DESCRIPTOR' : _COMMITRESPONSE,
  '__module__' : 'resemble.v1alpha1.transactions_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.CommitResponse)
  })
_sym_db.RegisterMessage(CommitResponse)

AbortRequest = _reflection.GeneratedProtocolMessageType('AbortRequest', (_message.Message,), {
  'DESCRIPTOR' : _ABORTREQUEST,
  '__module__' : 'resemble.v1alpha1.transactions_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.AbortRequest)
  })
_sym_db.RegisterMessage(AbortRequest)

AbortResponse = _reflection.GeneratedProtocolMessageType('AbortResponse', (_message.Message,), {
  'DESCRIPTOR' : _ABORTRESPONSE,
  '__module__' : 'resemble.v1alpha1.transactions_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.AbortResponse)
  })
_sym_db.RegisterMessage(AbortResponse)

WatchRequest = _reflection.GeneratedProtocolMessageType('WatchRequest', (_message.Message,), {
  'DESCRIPTOR' : _WATCHREQUEST,
  '__module__' : 'resemble.v1alpha1.transactions_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.WatchRequest)
  })
_sym_db.RegisterMessage(WatchRequest)

WatchResponse = _reflection.GeneratedProtocolMessageType('WatchResponse', (_message.Message,), {
  'DESCRIPTOR' : _WATCHRESPONSE,
  '__module__' : 'resemble.v1alpha1.transactions_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.WatchResponse)
  })
_sym_db.RegisterMessage(WatchResponse)

_PARTICIPANT = DESCRIPTOR.services_by_name['Participant']
_COORDINATOR = DESCRIPTOR.services_by_name['Coordinator']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PREPAREREQUEST._serialized_start=59
  _PREPAREREQUEST._serialized_end=134
  _PREPARERESPONSE._serialized_start=136
  _PREPARERESPONSE._serialized_end=153
  _COMMITREQUEST._serialized_start=155
  _COMMITREQUEST._serialized_end=229
  _COMMITRESPONSE._serialized_start=231
  _COMMITRESPONSE._serialized_end=247
  _ABORTREQUEST._serialized_start=249
  _ABORTREQUEST._serialized_end=322
  _ABORTRESPONSE._serialized_start=324
  _ABORTRESPONSE._serialized_end=339
  _WATCHREQUEST._serialized_start=341
  _WATCHREQUEST._serialized_end=379
  _WATCHRESPONSE._serialized_start=381
  _WATCHRESPONSE._serialized_end=413
  _PARTICIPANT._serialized_start=416
  _PARTICIPANT._serialized_end=666
  _COORDINATOR._serialized_start=668
  _COORDINATOR._serialized_end=757
# @@protoc_insertion_point(module_scope)
