# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ansys/api/edb/v1/simulation_setup.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ansys.api.edb.v1 import edb_messages_pb2 as ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2
try:
  google_dot_protobuf_dot_wrappers__pb2 = ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.google_dot_protobuf_dot_wrappers__pb2
except AttributeError:
  google_dot_protobuf_dot_wrappers__pb2 = ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.google.protobuf.wrappers_pb2
try:
  google_dot_protobuf_dot_empty__pb2 = ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.google_dot_protobuf_dot_empty__pb2
except AttributeError:
  google_dot_protobuf_dot_empty__pb2 = ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.google.protobuf.empty_pb2
from ansys.api.edb.v1 import edb_defs_pb2 as ansys_dot_api_dot_edb_dot_v1_dot_edb__defs__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'ansys/api/edb/v1/simulation_setup.proto\x12\x10\x61nsys.api.edb.v1\x1a#ansys/api/edb/v1/edb_messages.proto\x1a\x1f\x61nsys/api/edb/v1/edb_defs.proto\"\x92\x01\n\x1eSimulationSetupCreationMessage\x12-\n\x04\x63\x65ll\x18\x01 \x01(\x0b\x32\x1f.ansys.api.edb.v1.EDBObjMessage\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x33\n\x04type\x18\x03 \x01(\x0e\x32%.ansys.api.edb.v1.SimulationSetupType\"N\n\x10SweepDataMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x18\n\x10\x66requency_string\x18\x02 \x01(\t\x12\x12\n\nfast_sweep\x18\x03 \x01(\x08\"N\n\x14SweepDataListMessage\x12\x36\n\nsweep_data\x18\x01 \x03(\x0b\x32\".ansys.api.edb.v1.SweepDataMessage\"\x87\x01\n\x1cSweepDataListPropertyMessage\x12/\n\x06target\x18\x01 \x01(\x0b\x32\x1f.ansys.api.edb.v1.EDBObjMessage\x12\x36\n\x06sweeps\x18\x02 \x01(\x0b\x32&.ansys.api.edb.v1.SweepDataListMessage\"Q\n\x1aSimulationSetupTypeMessage\x12\x33\n\x04type\x18\x01 \x01(\x0e\x32%.ansys.api.edb.v1.SimulationSetupType2\xc4\x05\n\x16SimulationSetupService\x12]\n\x06\x43reate\x12\x30.ansys.api.edb.v1.SimulationSetupCreationMessage\x1a\x1f.ansys.api.edb.v1.EDBObjMessage\"\x00\x12J\n\x07GetName\x12\x1f.ansys.api.edb.v1.EDBObjMessage\x1a\x1c.google.protobuf.StringValue\"\x00\x12L\n\x07SetName\x12\'.ansys.api.edb.v1.StringPropertyMessage\x1a\x16.google.protobuf.Empty\"\x00\x12N\n\x0bGetPosition\x12\x1f.ansys.api.edb.v1.EDBObjMessage\x1a\x1c.google.protobuf.UInt64Value\"\x00\x12P\n\x0bSetPosition\x12\'.ansys.api.edb.v1.UInt64PropertyMessage\x1a\x16.google.protobuf.Empty\"\x00\x12Y\n\x0cGetSweepData\x12\x1f.ansys.api.edb.v1.EDBObjMessage\x1a&.ansys.api.edb.v1.SweepDataListMessage\"\x00\x12X\n\x0cSetSweepData\x12..ansys.api.edb.v1.SweepDataListPropertyMessage\x1a\x16.google.protobuf.Empty\"\x00\x12Z\n\x07GetType\x12\x1f.ansys.api.edb.v1.EDBObjMessage\x1a,.ansys.api.edb.v1.SimulationSetupTypeMessage\"\x00\x62\x06proto3')



_SIMULATIONSETUPCREATIONMESSAGE = DESCRIPTOR.message_types_by_name['SimulationSetupCreationMessage']
_SWEEPDATAMESSAGE = DESCRIPTOR.message_types_by_name['SweepDataMessage']
_SWEEPDATALISTMESSAGE = DESCRIPTOR.message_types_by_name['SweepDataListMessage']
_SWEEPDATALISTPROPERTYMESSAGE = DESCRIPTOR.message_types_by_name['SweepDataListPropertyMessage']
_SIMULATIONSETUPTYPEMESSAGE = DESCRIPTOR.message_types_by_name['SimulationSetupTypeMessage']
SimulationSetupCreationMessage = _reflection.GeneratedProtocolMessageType('SimulationSetupCreationMessage', (_message.Message,), {
  'DESCRIPTOR' : _SIMULATIONSETUPCREATIONMESSAGE,
  '__module__' : 'ansys.api.edb.v1.simulation_setup_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.SimulationSetupCreationMessage)
  })
_sym_db.RegisterMessage(SimulationSetupCreationMessage)

SweepDataMessage = _reflection.GeneratedProtocolMessageType('SweepDataMessage', (_message.Message,), {
  'DESCRIPTOR' : _SWEEPDATAMESSAGE,
  '__module__' : 'ansys.api.edb.v1.simulation_setup_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.SweepDataMessage)
  })
_sym_db.RegisterMessage(SweepDataMessage)

SweepDataListMessage = _reflection.GeneratedProtocolMessageType('SweepDataListMessage', (_message.Message,), {
  'DESCRIPTOR' : _SWEEPDATALISTMESSAGE,
  '__module__' : 'ansys.api.edb.v1.simulation_setup_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.SweepDataListMessage)
  })
_sym_db.RegisterMessage(SweepDataListMessage)

SweepDataListPropertyMessage = _reflection.GeneratedProtocolMessageType('SweepDataListPropertyMessage', (_message.Message,), {
  'DESCRIPTOR' : _SWEEPDATALISTPROPERTYMESSAGE,
  '__module__' : 'ansys.api.edb.v1.simulation_setup_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.SweepDataListPropertyMessage)
  })
_sym_db.RegisterMessage(SweepDataListPropertyMessage)

SimulationSetupTypeMessage = _reflection.GeneratedProtocolMessageType('SimulationSetupTypeMessage', (_message.Message,), {
  'DESCRIPTOR' : _SIMULATIONSETUPTYPEMESSAGE,
  '__module__' : 'ansys.api.edb.v1.simulation_setup_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.edb.v1.SimulationSetupTypeMessage)
  })
_sym_db.RegisterMessage(SimulationSetupTypeMessage)

_SIMULATIONSETUPSERVICE = DESCRIPTOR.services_by_name['SimulationSetupService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIMULATIONSETUPCREATIONMESSAGE._serialized_start=132
  _SIMULATIONSETUPCREATIONMESSAGE._serialized_end=278
  _SWEEPDATAMESSAGE._serialized_start=280
  _SWEEPDATAMESSAGE._serialized_end=358
  _SWEEPDATALISTMESSAGE._serialized_start=360
  _SWEEPDATALISTMESSAGE._serialized_end=438
  _SWEEPDATALISTPROPERTYMESSAGE._serialized_start=441
  _SWEEPDATALISTPROPERTYMESSAGE._serialized_end=576
  _SIMULATIONSETUPTYPEMESSAGE._serialized_start=578
  _SIMULATIONSETUPTYPEMESSAGE._serialized_end=659
  _SIMULATIONSETUPSERVICE._serialized_start=662
  _SIMULATIONSETUPSERVICE._serialized_end=1370
# @@protoc_insertion_point(module_scope)
