# coding: utf-8

"""
    BeeKeeperAI EscrowAI Enclave API

    Described below is the EscrowAI Enclave API that provides functionality inside a BeeKeeperAI environment. Included are data engineering endpoints and reporting endpoints.

    The version of the OpenAPI document: 1.5.0
    Contact: engineering@beekeeperai.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
from unittest.mock import MagicMock
import datetime
import json

import BeeKeeperRuntimeSDK
from BeeKeeperRuntimeSDK.models.ping_enclave_get200_response import PingEnclaveGet200Response  # noqa: E501
from BeeKeeperRuntimeSDK.rest import ApiException
from BeeKeeperRuntimeSDK.api_client import ApiClient

class TestPingEnclaveGet200Response(unittest.TestCase):
    """PingEnclaveGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PingEnclaveGet200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PingEnclaveGet200Response`
        """
        model = BeeKeeperRuntimeSDK.models.ping_enclave_get200_response.PingEnclaveGet200Response()  # noqa: E501
        if include_optional :
            return PingEnclaveGet200Response(
                status = ''
            )
        else :
            return PingEnclaveGet200Response(
                status = '',
        )
        """

    def testPingEnclaveGet200Response(self):
        """Test PingEnclaveGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

        ping_enclave_get200_response_json = None

        if ping_enclave_get200_response_json is None:
            return

        response_mock = MagicMock()
        response_mock.data = json.dumps(ping_enclave_get200_response_json)

        deserialized = ApiClient().deserialize(response_mock, PingEnclaveGet200Response)

        assert deserialized is not None

if __name__ == '__main__':
    unittest.main()
