# coding: utf-8

"""
    BeeKeeperAI EscrowAI Enclave API

    Described below is the EscrowAI Enclave API that provides functionality inside a BeeKeeperAI environment. Included are data engineering endpoints and reporting endpoints.

    The version of the OpenAPI document: 1.5.0
    Contact: engineering@beekeeperai.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
from unittest.mock import MagicMock
import datetime
import json

import BeeKeeperRuntimeSDK
from BeeKeeperRuntimeSDK.models.data_sql_select_post200_response import DataSqlSelectPost200Response  # noqa: E501
from BeeKeeperRuntimeSDK.rest import ApiException
from BeeKeeperRuntimeSDK.api_client import ApiClient

class TestDataSqlSelectPost200Response(unittest.TestCase):
    """DataSqlSelectPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test DataSqlSelectPost200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DataSqlSelectPost200Response`
        """
        model = BeeKeeperRuntimeSDK.models.data_sql_select_post200_response.DataSqlSelectPost200Response()  # noqa: E501
        if include_optional :
            return DataSqlSelectPost200Response(
                results = [
                    None
                    ], 
                message = ''
            )
        else :
            return DataSqlSelectPost200Response(
                results = [
                    None
                    ],
                message = '',
        )
        """

    def testDataSqlSelectPost200Response(self):
        """Test DataSqlSelectPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

        data_sql_select_post200_response_json = None

        if data_sql_select_post200_response_json is None:
            return

        response_mock = MagicMock()
        response_mock.data = json.dumps(data_sql_select_post200_response_json)

        deserialized = ApiClient().deserialize(response_mock, DataSqlSelectPost200Response)

        assert deserialized is not None

if __name__ == '__main__':
    unittest.main()
