# coding: utf-8

"""
    BeeKeeperAI EscrowAI Enclave API

    Described below is the EscrowAI Enclave API that provides functionality inside a BeeKeeperAI environment. Included are data engineering endpoints and reporting endpoints.

    The version of the OpenAPI document: 1.5.1
    Contact: engineering@beekeeperai.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
from unittest.mock import MagicMock
import datetime
import json

import BeeEnclave
from BeeEnclave.models.ping_key_manager_status import PingKeyManagerStatus  # noqa: E501
from BeeEnclave.rest import ApiException
from BeeEnclave.api_client import ApiClient

class TestPingKeyManagerStatus(unittest.TestCase):
    """PingKeyManagerStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PingKeyManagerStatus
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PingKeyManagerStatus`
        """
        model = BeeEnclave.models.ping_key_manager_status.PingKeyManagerStatus()  # noqa: E501
        if include_optional :
            return PingKeyManagerStatus(
                status = ''
            )
        else :
            return PingKeyManagerStatus(
                status = '',
        )
        """

    def testPingKeyManagerStatus(self):
        """Test PingKeyManagerStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

        ping_key_manager_status_json = None

        if ping_key_manager_status_json is None:
            return

        response_mock = MagicMock()
        response_mock.data = json.dumps(ping_key_manager_status_json)

        deserialized = ApiClient().deserialize(response_mock, PingKeyManagerStatus)

        assert deserialized is not None

if __name__ == '__main__':
    unittest.main()
