# coding: utf-8

"""
    BeeKeeperAI EscrowAI Enclave API

    Described below is the EscrowAI Enclave API that provides functionality inside a BeeKeeperAI environment. Included are data engineering endpoints and reporting endpoints.

    The version of the OpenAPI document: 1.5.0
    Contact: engineering@beekeeperai.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
from unittest.mock import MagicMock
import datetime
import json

import BeeKeeperRuntimeSDK
from BeeKeeperRuntimeSDK.models.report_post_request import ReportPostRequest  # noqa: E501
from BeeKeeperRuntimeSDK.rest import ApiException
from BeeKeeperRuntimeSDK.api_client import ApiClient

class TestReportPostRequest(unittest.TestCase):
    """ReportPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ReportPostRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReportPostRequest`
        """
        model = BeeKeeperRuntimeSDK.models.report_post_request.ReportPostRequest()  # noqa: E501
        if include_optional :
            return ReportPostRequest(
                name = '', 
                status = 'In Progress', 
                json_data = '', 
                upload_location = '', 
                project = '', 
                run_configuration = '', 
                run = ''
            )
        else :
            return ReportPostRequest(
                name = '',
                status = 'In Progress',
                json_data = '',
                upload_location = '',
                project = '',
                run_configuration = '',
                run = '',
        )
        """

    def testReportPostRequest(self):
        """Test ReportPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

        report_post_request_json = None

        if report_post_request_json is None:
            return

        response_mock = MagicMock()
        response_mock.data = json.dumps(report_post_request_json)

        deserialized = ApiClient().deserialize(response_mock, ReportPostRequest)

        assert deserialized is not None
        assert deserialized.name == report_post_request_json.get("name")
        assert deserialized.status == report_post_request_json.get("status")
        assert deserialized.json_data == report_post_request_json.get("json_data")
        assert deserialized.upload_location == report_post_request_json.get("upload_location")
        assert deserialized.project == report_post_request_json.get("project")
        assert deserialized.run_configuration == report_post_request_json.get("run_configuration")
        assert deserialized.run == report_post_request_json.get("run")

if __name__ == '__main__':
    unittest.main()
