# Generated by Django 4.2.9 on 2024-01-17 22:56

import crontab._crontab
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('limit', models.CharField(default=None, max_length=500, null=True)),
                ('verbosity', models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'v'), (2, 'vv'), (3, 'vvv'), (4, 'vvvv'), (5, 'vvvv'), (6, 'vvvvvv')], default=0)),
                ('environment_vars', models.CharField(default=None, max_length=1000, null=True)),
                ('job_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('inventory', models.CharField(max_length=300)),
                ('playbook', models.CharField(max_length=300)),
                ('schedule', models.CharField(max_length=50, validators=[crontab._crontab.CronTab])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('short', models.CharField(max_length=100)),
                ('med', models.TextField(max_length=1024, null=True)),
                ('logfile', models.FilePathField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobExecutionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('time_start', models.DateTimeField(auto_now_add=True)),
                ('time_fin', models.DateTimeField(blank=True, default=None, null=True)),
                ('failed', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('permission', models.CharField(choices=[('full', 'Full'), ('read', 'Read'), ('write', 'Write'), ('execute', 'Execute')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobPermissionMemberUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aw.jobpermission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobPermissionMemberGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aw.jobpermission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='jobpermission',
            name='groups',
            field=models.ManyToManyField(through='aw.JobPermissionMemberGroup', to='auth.group'),
        ),
        migrations.AddField(
            model_name='jobpermission',
            name='users',
            field=models.ManyToManyField(through='aw.JobPermissionMemberUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='JobExecutionResultHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('hostname', models.CharField(max_length=300)),
                ('unreachable', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('tasks_skipped', models.PositiveSmallIntegerField(default=0)),
                ('tasks_ok', models.PositiveSmallIntegerField(default=0)),
                ('tasks_failed', models.PositiveSmallIntegerField(default=0)),
                ('tasks_rescued', models.PositiveSmallIntegerField(default=0)),
                ('tasks_ignored', models.PositiveSmallIntegerField(default=0)),
                ('tasks_changed', models.PositiveSmallIntegerField(default=0)),
                ('error', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobresulthost_fk_error', to='aw.joberror')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobresulthost_fk_result', to='aw.jobexecutionresult')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('limit', models.CharField(default=None, max_length=500, null=True)),
                ('verbosity', models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'v'), (2, 'vv'), (3, 'vvv'), (4, 'vvvv'), (5, 'vvvv'), (6, 'vvvvvv')], default=0)),
                ('environment_vars', models.CharField(default=None, max_length=1000, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Waiting'), (1, 'Starting'), (2, 'Running'), (3, 'Failed'), (4, 'Finished')], default=0)),
                ('comment', models.CharField(default=None, max_length=300, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobexec_fk_job', to='aw.job')),
                ('result', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobexec_fk_result', to='aw.jobexecutionresult')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobexec_fk_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='job',
            name='permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aw.jobpermission'),
        ),
    ]
