# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class LitpagesIdBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'content': 'str',
        'order': 'int',
        'parent_id': 'str'
    }

    attribute_map = {
        'content': 'content',
        'order': 'order',
        'parent_id': 'parentId'
    }

    def __init__(self, content: 'str' =None, order: 'int' =None, parent_id: 'str' =None):  # noqa: E501
        """LitpagesIdBody - a model defined in Swagger"""  # noqa: E501
        self._content = None
        self._order = None
        self._parent_id = None
        self.discriminator = None
        if content is not None:
            self.content = content
        if order is not None:
            self.order = order
        if parent_id is not None:
            self.parent_id = parent_id

    @property
    def content(self) -> 'str':
        """Gets the content of this LitpagesIdBody.  # noqa: E501


        :return: The content of this LitpagesIdBody.  # noqa: E501
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content: 'str'):
        """Sets the content of this LitpagesIdBody.


        :param content: The content of this LitpagesIdBody.  # noqa: E501
        :type: str
        """

        self._content = content

    @property
    def order(self) -> 'int':
        """Gets the order of this LitpagesIdBody.  # noqa: E501


        :return: The order of this LitpagesIdBody.  # noqa: E501
        :rtype: int
        """
        return self._order

    @order.setter
    def order(self, order: 'int'):
        """Sets the order of this LitpagesIdBody.


        :param order: The order of this LitpagesIdBody.  # noqa: E501
        :type: int
        """

        self._order = order

    @property
    def parent_id(self) -> 'str':
        """Gets the parent_id of this LitpagesIdBody.  # noqa: E501


        :return: The parent_id of this LitpagesIdBody.  # noqa: E501
        :rtype: str
        """
        return self._parent_id

    @parent_id.setter
    def parent_id(self, parent_id: 'str'):
        """Sets the parent_id of this LitpagesIdBody.


        :param parent_id: The parent_id of this LitpagesIdBody.  # noqa: E501
        :type: str
        """

        self._parent_id = parent_id

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LitpagesIdBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'LitpagesIdBody') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, LitpagesIdBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'LitpagesIdBody') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
