
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-17T15:07:09+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c8120d86a0bd05165c38fafb17dc84752f23c76a",
 "version": "1.21.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
