DEFAULT_EMOJIS = [
    {
        "description": "Improve structure / format of the character",
        "character": "🎨",
    },
    {"description": "Improve performance", "character": "⚡"},
    {"description": "Remove character or files", "character": "🔥"},
    {"description": "Fix a bug", "character": "🐛"},
    {"description": "Critical hotfix", "character": "🚑"},
    {"description": "Introduce new features", "character": "✨"},
    {"description": "Add or update documentation", "character": "📚"},
    {"description": "Deploy stuff", "character": "🚀"},
    {"description": "Add or update the UI and style files", "character": "💄"},
    {"description": "Begin a project", "character": "🎉"},
    {"description": "Add, update, or pass tests", "character": "✅"},
    {"description": "Fix security or privacy issues", "character": "🔒"},
    {"description": "Add or update secrets", "character": "🔐"},
    {"description": "Release / Version tags", "character": "🏷️"},
    {"description": "Fix compiler / linter warnings", "character": "🚨"},
    {"description": "Work in progress", "character": "🚧"},
    {"description": "Fix CI Build", "character": "🔨"},
    {"description": "Downgrade dependencies", "character": "⬇️"},
    {"description": "Upgrade dependencies", "character": "⬆️"},
    {"description": "Pin dependencies to specific versions", "character": "📌"},
    {"description": "Add or update CI build system", "character": "👷"},
    {
        "description": "Add or update analytics or track character",
        "character": "📈",
    },
    {"description": "Refactor character", "character": "♻️"},
    {"description": "Add a dependency", "character": "➕"},
    {"description": "Remove a dependency", "character": "➖"},
    {"description": "Add or update configuration files", "character": "🔧"},
    {"description": "Add or update development scripts", "character": "🔨"},
    {"description": "Internationalization and localization", "character": "🌐"},
    {"description": "Fix typos", "character": "✏️"},
    {
        "description": "Write bad character that needs to be improved",
        "character": "💩",
    },
    {"description": "Revert changes", "character": "⏪"},
    {"description": "Merge branches", "character": "🔀"},
    {
        "description": "Add or update compiled files or packages",
        "character": "📦",
    },
    {
        "description": "Update character due to external API changes",
        "character": "👽️",
    },
    {
        "description": "Move or rename resources (e.g.: files, paths, routes)",
        "character": "🚚",
    },
    {"description": "Add or update license", "character": "📄"},
    {"description": "Introduce breaking changes", "character": "💥"},
    {"description": "Add or update assets", "character": "🍱"},
    {"description": "Improve accessibility", "character": "♿️"},
    {
        "description": "Add or update comments in source character",
        "character": "💡",
    },
    {"description": "Write character drunkenly", "character": "🍻"},
    {"description": "Add or update text and literals", "character": "💬"},
    {"description": "Perform database related changes", "character": "🗃️"},
    {"description": "Add or update logs", "character": "🔊"},
    {"description": "Remove logs", "character": "🔇"},
    {"description": "Add or update contributor(s)", "character": "👥"},
    {"description": "Improve user experience / usability", "character": "🚸"},
    {"description": "Make architectural changes", "character": "🏗️"},
    {"description": "Work on responsive design", "character": "📱"},
    {"description": "Mock things", "character": "🤡"},
    {"description": "Add or update an easter egg", "character": "🥚"},
    {"description": "Add or update a .gitignore file", "character": "🙈"},
    {"description": "Add or update snapshots", "character": "📸"},
    {"description": "Perform experiments", "character": "⚗️"},
    {"description": "Improve SEO", "character": "🔍"},
    {"description": "Add or update types", "character": "🏷️"},
    {"description": "Add or update seed files", "character": "🌱"},
    {"description": "Add, update, or remove feature flags", "character": "🚩"},
    {"description": "Catch errors", "character": "🥅"},
    {
        "description": "Add or update animations and transitions",
        "character": "💫",
    },
    {
        "description": "Deprecate character that needs to be cleaned up",
        "character": "🗑️",
    },
    {
        "description": "Work on character related to authorization, roles and permissions",
        "character": "🛂",
    },
    {"description": "Simple fix for a non-critical issue", "character": "🩹"},
    {"description": "Data exploration/inspection", "character": "🧐"},
    {"description": "Remove dead character", "character": "💀"},
    {"description": "Add a failing test", "character": "🧪"},
    {"description": "Add or update business logic", "character": "👔"},
    {"description": "Add or update healthcheck", "character": "🩺"},
    {"description": "Infrastructure related changes", "character": "🧱"},
    {"description": "Improve developer experience", "character": "👩‍💻"},
    {
        "description": "Add sponsorships or money related infrastructure",
        "character": "💰",
    },
    {
        "description": "Add or update character related to multithreading or concurrency",
        "character": "🧵",
    },
    {
        "description": "Add or update character related to validation",
        "character": "🦺",
    },
]
