# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: unacast/unatype/availability.proto, unacast/unatype/date.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class AvailabilityKind(betterproto.Enum):
    ALL = 0
    DELIVERY_ONLY = 1


@dataclass(eq=False, repr=False)
class Date(betterproto.Message):
    """
    TODO: consider using googles implementation instead, google.type.Date
    """

    year: int = betterproto.int32_field(1)
    month: int = betterproto.int32_field(2)
    day: int = betterproto.int32_field(3)


@dataclass(eq=False, repr=False)
class DateRange(betterproto.Message):
    start: "Date" = betterproto.message_field(1)
    end: "Date" = betterproto.message_field(2)
