
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-16T10:44:36-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "72d85da6b854b39f9ac94a05bced41e77f45ad78",
 "version": "4.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
