
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-17T12:47:09+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6b185cbad438528354fc9083b7f2f3db7f3927a1",
 "version": "5.5.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
