from nwon_deployment.typings import DockerService as DockerService, DockerServiceActionMap as DockerServiceActionMap
from typing import Optional

def start_or_update_service(service: DockerService): ...
def start_service(service: DockerService, action_map: Optional[DockerServiceActionMap[DockerService]] = ...): ...
def restart_service(service: DockerService, action_map: Optional[DockerServiceActionMap[DockerService]] = ...): ...
