
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-17T13:36:11+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "49a3bab9832777d6abe01423db766249aa3096a4",
 "version": "5.5.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
