# Generated by Django 4.2.3 on 2023-10-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cosmic_pipeline", "0002_transition_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="transition",
            name="post_change_processor",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
