# Generated by Django 4.2.3 on 2023-10-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cosmic_pipeline", "0003_transition_post_change_processor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transition",
            name="post_change_processor",
            field=models.CharField(
                blank=True,
                choices=[
                    ("send_email", "Send Email"),
                    ("send_sms", "Send SMS"),
                    ("send_sms_email", "Send SMS and Email"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
