# Generated by Django 4.2.3 on 2023-12-07 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("cosmic_pipeline", "0004_alter_transition_post_change_processor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="workflow_model",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workflows",
                to="contenttypes.contenttype",
                verbose_name="Workflow Model",
            ),
        ),
    ]
