from nwon_deployment.typings import ContainerInformation as ContainerInformation, DockerService as DockerService
from typing import List, Optional

def containers_for_service(service: DockerService) -> List[ContainerInformation]: ...
def max_service_index(service: DockerService) -> Optional[int]: ...
