'''
## This file is autogenerated from macrosynergy setup.py.

It contains version information for the macrosynergy package.

short_version: 0.1.3

version: 0.1.3

full_version: 0.1.3

git_revision: 7842eb74f0b49bd505079fef1290dd21ef87937e

release: True

'''
short_version: str = '0.1.3'
version: str = '0.1.3'
full_version: str = '0.1.3'
git_revision: str = '7842eb74f0b49bd505079fef1290dd21ef87937e'
release: bool = True
if not release:
    version = full_version
