
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-11T14:19:01+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "fb65d1f92910d9d6874fa59b58719538fd74f5d5",
 "version": "1.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
