# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resemble/v1alpha1/inspect/inspect.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from resemble.v1alpha1 import options_pb2 as resemble_dot_v1alpha1_dot_options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'resemble/v1alpha1/inspect/inspect.proto\x12\x19resemble.v1alpha1.inspect\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fresemble/v1alpha1/options.proto\"\x15\n\x13GetAllActorsRequest\"?\n\x14GetAllActorsResponse\x12\'\n\x06\x61\x63tors\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"\x0e\n\x0cInspectState2\xda\x01\n\x07Inspect\x12@\n\x06\x43reate\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x06\x82\xb5\x18\x02\x12\x00\x12y\n\x0cGetAllActors\x12..resemble.v1alpha1.inspect.GetAllActorsRequest\x1a/.resemble.v1alpha1.inspect.GetAllActorsResponse\"\x06\x82\xb5\x18\x02\n\x00\x30\x01\x1a\x12\x82\xb5\x18\x0e\n\x0cInspectStateb\x06proto3')



_GETALLACTORSREQUEST = DESCRIPTOR.message_types_by_name['GetAllActorsRequest']
_GETALLACTORSRESPONSE = DESCRIPTOR.message_types_by_name['GetAllActorsResponse']
_INSPECTSTATE = DESCRIPTOR.message_types_by_name['InspectState']
GetAllActorsRequest = _reflection.GeneratedProtocolMessageType('GetAllActorsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETALLACTORSREQUEST,
  '__module__' : 'resemble.v1alpha1.inspect.inspect_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.inspect.GetAllActorsRequest)
  })
_sym_db.RegisterMessage(GetAllActorsRequest)

GetAllActorsResponse = _reflection.GeneratedProtocolMessageType('GetAllActorsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETALLACTORSRESPONSE,
  '__module__' : 'resemble.v1alpha1.inspect.inspect_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.inspect.GetAllActorsResponse)
  })
_sym_db.RegisterMessage(GetAllActorsResponse)

InspectState = _reflection.GeneratedProtocolMessageType('InspectState', (_message.Message,), {
  'DESCRIPTOR' : _INSPECTSTATE,
  '__module__' : 'resemble.v1alpha1.inspect.inspect_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.inspect.InspectState)
  })
_sym_db.RegisterMessage(InspectState)

_INSPECT = DESCRIPTOR.services_by_name['Inspect']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INSPECT._options = None
  _INSPECT._serialized_options = b'\202\265\030\016\n\014InspectState'
  _INSPECT.methods_by_name['Create']._options = None
  _INSPECT.methods_by_name['Create']._serialized_options = b'\202\265\030\002\022\000'
  _INSPECT.methods_by_name['GetAllActors']._options = None
  _INSPECT.methods_by_name['GetAllActors']._serialized_options = b'\202\265\030\002\n\000'
  _GETALLACTORSREQUEST._serialized_start=162
  _GETALLACTORSREQUEST._serialized_end=183
  _GETALLACTORSRESPONSE._serialized_start=185
  _GETALLACTORSRESPONSE._serialized_end=248
  _INSPECTSTATE._serialized_start=250
  _INSPECTSTATE._serialized_end=264
  _INSPECT._serialized_start=267
  _INSPECT._serialized_end=485
# @@protoc_insertion_point(module_scope)
