# coding: utf-8

"""
    BeeKeeperAI EscrowAI Enclave API

    Described below is the EscrowAI Enclave API that provides functionality inside a BeeKeeperAI environment. Included are data engineering endpoints and reporting endpoints.

    The version of the OpenAPI document: 1.5.1
    Contact: engineering@beekeeperai.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
from unittest.mock import MagicMock
import datetime
import json

import BeeEnclave
from BeeEnclave.models.file import File  # noqa: E501
from BeeEnclave.rest import ApiException
from BeeEnclave.api_client import ApiClient

class TestFile(unittest.TestCase):
    """File unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test File
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `File`
        """
        model = BeeEnclave.models.file.File()  # noqa: E501
        if include_optional :
            return File(
                id = '', 
                name = '', 
                size = 56, 
                upload_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else :
            return File(
                id = '',
                name = '',
                size = 56,
                upload_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testFile(self):
        """Test File"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

        file_json = {"id": "f47ac10b-58cc-4372-a567-0e02b2c3d479", "name": "Kirin", "size": 6, "uploadDate": "2023-03-17 00:35:06.758+03"}

        if file_json is None:
            return

        response_mock = MagicMock()
        response_mock.data = json.dumps(file_json)

        deserialized = ApiClient().deserialize(response_mock, File)

        assert deserialized is not None

if __name__ == '__main__':
    unittest.main()
