
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-15T21:12:33+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "eb82a6f4bf39efd3585a069dc8faea8e392a370c",
 "version": "0.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
