# coding: utf-8

# flake8: noqa
"""
    腾讯会议OpenAPI

    SAAS版RESTFUL风格API

    API version: v1.0.0.15

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from wemeet_openapi.service.meetings.model.v1_meeting_set_waiting_room_welcome_message_post200_response import V1MeetingSetWaitingRoomWelcomeMessagePost200Response
from wemeet_openapi.service.meetings.model.v1_meeting_set_waiting_room_welcome_message_post_request import V1MeetingSetWaitingRoomWelcomeMessagePostRequest
from wemeet_openapi.service.meetings.model.v1_meetings_get200_response import V1MeetingsGet200Response
from wemeet_openapi.service.meetings.model.v1_meetings_get200_response_meeting_info_list_inner import V1MeetingsGet200ResponseMeetingInfoListInner
from wemeet_openapi.service.meetings.model.v1_meetings_get200_response_meeting_info_list_inner_current_co_hosts_inner import V1MeetingsGet200ResponseMeetingInfoListInnerCurrentCoHostsInner
from wemeet_openapi.service.meetings.model.v1_meetings_get200_response_meeting_info_list_inner_current_hosts_inner import V1MeetingsGet200ResponseMeetingInfoListInnerCurrentHostsInner
from wemeet_openapi.service.meetings.model.v1_meetings_get200_response_meeting_info_list_inner_guests_inner import V1MeetingsGet200ResponseMeetingInfoListInnerGuestsInner
from wemeet_openapi.service.meetings.model.v1_meetings_get200_response_meeting_info_list_inner_live_config import V1MeetingsGet200ResponseMeetingInfoListInnerLiveConfig
from wemeet_openapi.service.meetings.model.v1_meetings_get200_response_meeting_info_list_inner_live_config_live_watermark import V1MeetingsGet200ResponseMeetingInfoListInnerLiveConfigLiveWatermark
from wemeet_openapi.service.meetings.model.v1_meetings_get200_response_meeting_info_list_inner_recurring_rule import V1MeetingsGet200ResponseMeetingInfoListInnerRecurringRule
from wemeet_openapi.service.meetings.model.v1_meetings_get200_response_meeting_info_list_inner_settings import V1MeetingsGet200ResponseMeetingInfoListInnerSettings
from wemeet_openapi.service.meetings.model.v1_meetings_get200_response_meeting_info_list_inner_sub_meetings_inner import V1MeetingsGet200ResponseMeetingInfoListInnerSubMeetingsInner
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_cancel_post_request import V1MeetingsMeetingIdCancelPostRequest
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_enroll_approvals_get200_response import V1MeetingsMeetingIdEnrollApprovalsGet200Response
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_enroll_approvals_get200_response_enroll_list_inner import V1MeetingsMeetingIdEnrollApprovalsGet200ResponseEnrollListInner
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_enroll_approvals_get200_response_enroll_list_inner_answer_list_inner import V1MeetingsMeetingIdEnrollApprovalsGet200ResponseEnrollListInnerAnswerListInner
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_enroll_approvals_put200_response import V1MeetingsMeetingIdEnrollApprovalsPut200Response
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_enroll_approvals_put_request import V1MeetingsMeetingIdEnrollApprovalsPutRequest
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_enroll_config_get200_response import V1MeetingsMeetingIdEnrollConfigGet200Response
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_enroll_config_get200_response_question_list_inner import V1MeetingsMeetingIdEnrollConfigGet200ResponseQuestionListInner
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_enroll_config_get200_response_question_list_inner_option_list_inner import V1MeetingsMeetingIdEnrollConfigGet200ResponseQuestionListInnerOptionListInner
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_enroll_config_put200_response import V1MeetingsMeetingIdEnrollConfigPut200Response
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_enroll_config_put_request import V1MeetingsMeetingIdEnrollConfigPutRequest
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_enroll_config_put_request_question_list_inner import V1MeetingsMeetingIdEnrollConfigPutRequestQuestionListInner
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_enroll_config_put_request_question_list_inner_option_list_inner import V1MeetingsMeetingIdEnrollConfigPutRequestQuestionListInnerOptionListInner
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_enroll_ids_post200_response import V1MeetingsMeetingIdEnrollIdsPost200Response
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_enroll_ids_post200_response_enroll_id_list_inner import V1MeetingsMeetingIdEnrollIdsPost200ResponseEnrollIdListInner
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_enroll_ids_post_request import V1MeetingsMeetingIdEnrollIdsPostRequest
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_enroll_import_post200_response import V1MeetingsMeetingIdEnrollImportPost200Response
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_enroll_import_post200_response_enroll_list_inner import V1MeetingsMeetingIdEnrollImportPost200ResponseEnrollListInner
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_enroll_import_post_request import V1MeetingsMeetingIdEnrollImportPostRequest
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_enroll_import_post_request_enroll_list_inner import V1MeetingsMeetingIdEnrollImportPostRequestEnrollListInner
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_enroll_unregistration_delete200_response import V1MeetingsMeetingIdEnrollUnregistrationDelete200Response
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_enroll_unregistration_delete_request import V1MeetingsMeetingIdEnrollUnregistrationDeleteRequest
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_enroll_unregistration_delete_request_enroll_id_list_inner import V1MeetingsMeetingIdEnrollUnregistrationDeleteRequestEnrollIdListInner
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_get200_response import V1MeetingsMeetingIdGet200Response
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_get200_response_meeting_info_list_inner import V1MeetingsMeetingIdGet200ResponseMeetingInfoListInner
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_get200_response_meeting_info_list_inner_live_config import V1MeetingsMeetingIdGet200ResponseMeetingInfoListInnerLiveConfig
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_get200_response_meeting_info_list_inner_recurring_rule import V1MeetingsMeetingIdGet200ResponseMeetingInfoListInnerRecurringRule
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_get200_response_meeting_info_list_inner_sub_meetings_inner import V1MeetingsMeetingIdGet200ResponseMeetingInfoListInnerSubMeetingsInner
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_put200_response import V1MeetingsMeetingIdPut200Response
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_put200_response_meeting_info_list_inner import V1MeetingsMeetingIdPut200ResponseMeetingInfoListInner
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_put200_response_meeting_info_list_inner_live_config import V1MeetingsMeetingIdPut200ResponseMeetingInfoListInnerLiveConfig
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_put_request import V1MeetingsMeetingIdPutRequest
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_put_request_hosts_inner import V1MeetingsMeetingIdPutRequestHostsInner
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_put_request_live_config import V1MeetingsMeetingIdPutRequestLiveConfig
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_put_request_live_config_live_watermark import V1MeetingsMeetingIdPutRequestLiveConfigLiveWatermark
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_put_request_recurring_rule import V1MeetingsMeetingIdPutRequestRecurringRule
from wemeet_openapi.service.meetings.model.v1_meetings_meeting_id_put_request_settings import V1MeetingsMeetingIdPutRequestSettings
from wemeet_openapi.service.meetings.model.v1_meetings_post200_response import V1MeetingsPost200Response
from wemeet_openapi.service.meetings.model.v1_meetings_post200_response_meeting_info_list_inner import V1MeetingsPost200ResponseMeetingInfoListInner
from wemeet_openapi.service.meetings.model.v1_meetings_post200_response_meeting_info_list_inner_hosts_inner import V1MeetingsPost200ResponseMeetingInfoListInnerHostsInner
from wemeet_openapi.service.meetings.model.v1_meetings_post200_response_meeting_info_list_inner_live_config import V1MeetingsPost200ResponseMeetingInfoListInnerLiveConfig
from wemeet_openapi.service.meetings.model.v1_meetings_post200_response_meeting_info_list_inner_settings import V1MeetingsPost200ResponseMeetingInfoListInnerSettings
from wemeet_openapi.service.meetings.model.v1_meetings_post_request import V1MeetingsPostRequest
from wemeet_openapi.service.meetings.model.v1_meetings_post_request_guests_inner import V1MeetingsPostRequestGuestsInner
from wemeet_openapi.service.meetings.model.v1_meetings_post_request_hosts_inner import V1MeetingsPostRequestHostsInner
from wemeet_openapi.service.meetings.model.v1_meetings_post_request_invitees_inner import V1MeetingsPostRequestInviteesInner
from wemeet_openapi.service.meetings.model.v1_meetings_post_request_live_config import V1MeetingsPostRequestLiveConfig
from wemeet_openapi.service.meetings.model.v1_meetings_post_request_live_config_live_watermark import V1MeetingsPostRequestLiveConfigLiveWatermark
from wemeet_openapi.service.meetings.model.v1_meetings_post_request_recurring_rule import V1MeetingsPostRequestRecurringRule
from wemeet_openapi.service.meetings.model.v1_meetings_post_request_settings import V1MeetingsPostRequestSettings
