# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_ncls.ipynb.

# %% auto 0
__all__ = ['GEN', 'CON', 'DEC', 'RAW', 'DUCK', 'META', 'GUARD', 'TYPEGUARD', 'NAMESPACE', 'GENERATOR', 'CONSTRUCT', 'DECORATOR']

# %% ../nbs/10_ncls.ipynb 5
GEN = 'gen'
CON = 'con'
DEC = 'dec'
RAW = 'raw'


DUCK = 'duck'
META = 'meta'

GUARD = 'guard'
TYPEGUARD = f'TYPE{GUARD}'


NAMESPACE = 'namespace'
GENERATOR = 'generator'
CONSTRUCT = 'construct'
DECORATOR = 'decorator'

# %% ../nbs/10_ncls.ipynb 6
#| export

