# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commander.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63ommander.proto\x12\x07\x62\x61uplan\"\xbb\x01\n\x10JobCompleteEvent\x12#\n\x07success\x18\x01 \x01(\x0b\x32\x10.bauplan.SuccessH\x00\x12#\n\x07\x66\x61ilure\x18\x02 \x01(\x0b\x32\x10.bauplan.FailureH\x00\x12-\n\x0c\x63\x61ncellation\x18\x03 \x01(\x0b\x32\x15.bauplan.CancellationH\x00\x12#\n\x07timeout\x18\x04 \x01(\x0b\x32\x10.bauplan.TimeoutH\x00\x42\t\n\x07outcome\"\x1a\n\x07Success\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x85\x01\n\x07\x46\x61ilure\x12%\n\tcomponent\x18\x01 \x01(\x0e\x32\x12.bauplan.Component\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x12\n\nerror_code\x18\x03 \x01(\x05\x12\x18\n\x0bstack_trace\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\x0e\n\x0c_stack_trace\"\x1e\n\x0c\x43\x61ncellation\x12\x0e\n\x06reason\x18\x01 \x01(\t\"\x1a\n\x07Timeout\x12\x0f\n\x07message\x18\x01 \x01(\t*$\n\tComponent\x12\n\n\x06Runner\x10\x00\x12\x0b\n\x07Runtime\x10\x01\x42?Z=github.com/BauplanLabs/playground/commander-service/protobufsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'commander_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z=github.com/BauplanLabs/playground/commander-service/protobufs'
  _globals['_COMPONENT']._serialized_start=442
  _globals['_COMPONENT']._serialized_end=478
  _globals['_JOBCOMPLETEEVENT']._serialized_start=29
  _globals['_JOBCOMPLETEEVENT']._serialized_end=216
  _globals['_SUCCESS']._serialized_start=218
  _globals['_SUCCESS']._serialized_end=244
  _globals['_FAILURE']._serialized_start=247
  _globals['_FAILURE']._serialized_end=380
  _globals['_CANCELLATION']._serialized_start=382
  _globals['_CANCELLATION']._serialized_end=412
  _globals['_TIMEOUT']._serialized_start=414
  _globals['_TIMEOUT']._serialized_end=440
# @@protoc_insertion_point(module_scope)
