# Generated by Django 4.2.3 on 2024-01-17 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schelements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoDocHead",
            fields=[
                (
                    "dochead_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="schelements.dochead",
                    ),
                ),
                (
                    "date_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date from"
                    ),
                ),
                (
                    "date_to",
                    models.DateTimeField(blank=True, null=True, verbose_name="Date to"),
                ),
                (
                    "test",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="Test"
                    ),
                ),
            ],
            options={
                "verbose_name": "Demo document head",
                "verbose_name_plural": "Demo document heads",
                "ordering": ["id"],
                "default_permissions": ("add", "change", "delete", "list"),
            },
            bases=("schelements.dochead",),
        ),
        migrations.CreateModel(
            name="DemoDocItem",
            fields=[
                (
                    "docitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="schelements.docitem",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("1", "low"), ("9", "high")],
                        default="1",
                        max_length=1,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "date_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date from"
                    ),
                ),
                (
                    "date_to",
                    models.DateTimeField(blank=True, null=True, verbose_name="Date to"),
                ),
            ],
            options={
                "verbose_name": "Demo document item",
                "verbose_name_plural": "Demo document items",
                "ordering": ["id"],
                "default_permissions": ("add", "change", "delete", "list"),
            },
            bases=("schelements.docitem",),
        ),
    ]
