# Generated by Django 2.2.27 on 2022-06-10 10:07

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("djangocms_dag_jetcode", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jetcode",
            name="jetcode_type",
            field=models.CharField(
                choices=[
                    ("product", "Product"),
                    ("productselector", "Product selector"),
                    ("container", "Product list"),
                    ("package", "Package"),
                ],
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="jetcode",
            name="styles",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True, max_length=200, null=True, verbose_name="Styles"
            ),
        ),
    ]
