
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-19T17:13:07+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "89a68eaca7fc60c1506b678b6aa6646ef9a21b71",
 "version": "8.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
