# coding: utf-8

"""
    Lookup/Ibis web service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class ContactPhoneNumber(BaseModel):
    """
    Class representing a phone number held on an institution contact row, for use by the web service API.
    """
    phone_type: Optional[StrictStr] = Field(None, alias="phoneType", description="The phone number's type.")
    number: Optional[StrictStr] = Field(None, description="The phone number.")
    comment: Optional[StrictStr] = Field(None, description="Any comment associated with the phone number.")
    __properties = ["phoneType", "number", "comment"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ContactPhoneNumber:
        """Create an instance of ContactPhoneNumber from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ContactPhoneNumber:
        """Create an instance of ContactPhoneNumber from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ContactPhoneNumber.parse_obj(obj)

        _obj = ContactPhoneNumber.parse_obj({
            "phone_type": obj.get("phoneType"),
            "number": obj.get("number"),
            "comment": obj.get("comment")
        })
        return _obj


