VERSION_YEAR = 2024
VERSION_MONTH = int('01')
VERSION_DAY = int('16')
VERSION_HOUR = int('21')
VERSION_MINUTE = int('34')
MAJOR_VERSION = 1
MINOR_VERSION = 10
PATCH_VERSION = 202401162134
version_date = '2024/01/16 21:34'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
