
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-19T17:14:28+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "fb3985e95fbb3e6cb51a321d6d6a9a10661128fe",
 "version": "0.8.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
