
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-17T13:48:40+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "431fd42f30f47c3415359e62d8a730fb2730320b",
 "version": "0.1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
