
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-17T14:33:02-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "363f5ed9d0168b4ccfd5124e891f1e147b196f78",
 "version": "2.9.18.post0.dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
